id: I395A8B68
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T03:08:55+00:00'
last_modified: '2022-06-08T09:51:16.849438+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22024
  title: མི་མཇེད་འཇིག་རྟེན་ཁམས་ཀྱི་རྣམ་གཞག་གནའ་རབས་པའི་འདོད་ཚུལ་ལ་དཔྱད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E446:
      image_group_id: I1KG22305
      title: ''
      total_pages: 27
      order: 1
      base_file: E446.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
