id: P009274
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:31:06.235322
source_metadata:
  id: bdr:W1KG22024
  title: མི་མཇེད་འཇིག་རྟེན་ཁམས་ཀྱི་རྣམ་གཞག་གནའ་རབས་པའི་འདོད་ཚུལ་ལ་དཔྱད་པ།
  author: ''
  volumes:
    4443ed036e8a400384824b973004ff40:
      image_group_id: I1KG22305
      title: ''
      volume_number: 1
      total_pages: 27
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
